# -*- coding: utf-8 -*-
"""6_bit_quantized.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UfSNmWxUDiilBptkb3mwbClGgKoaSAGz
"""

# Python code to show all the floating-point values and their corresponding 6-bit binary values
# for a quantization range of 0 to 1 with 6-bit precision.

# Number of bits for quantization
bits = 6
# Total number of levels
levels = 2 ** bits
# Step size
step_size = 1 / levels

# Function to convert an integer to a 6-bit binary string
def int_to_binary6(value):
    return format(value, '06b')

# Generating and displaying all floating-point values and their corresponding binary representations
quantized_values = []
for i in range(levels):
    float_value = i * step_size
    binary_value = int_to_binary6(i)
    quantized_values.append((float_value, binary_value))

quantized_values

